site:
  title: वर्षाजलसंचयन 
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://antora.gitlab.io/demo/docs-site
  start_page: index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    start_path: docs
    edit_url: false
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
    
output:
  dir: ./build/site